/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 25-окт.-2023 00:20:52 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS cart_cart_user_id_seq
;

DROP SEQUENCE IF EXISTS category_category_id_seq
;

DROP SEQUENCE IF EXISTS m2m_product_size_color_m2m_psc_id_seq
;

DROP SEQUENCE IF EXISTS product_product_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Cart" CASCADE
;

DROP TABLE IF EXISTS "Category" CASCADE
;

DROP TABLE IF EXISTS "M2M_Product_Size_Color" CASCADE
;

DROP TABLE IF EXISTS "Product" CASCADE
;

/* Create Tables */

CREATE TABLE "Cart"
(
	cart_user_id bigint NOT NULL   DEFAULT NEXTVAL(('"cart_cart_user_id_seq"'::text)::regclass),
	cart_product_id bigint NOT NULL,
	cart_quantity smallint NULL
)
;

CREATE TABLE "Category"
(
	category_id bigint NOT NULL   DEFAULT NEXTVAL(('"category_category_id_seq"'::text)::regclass),
	category_subcategory_id bigint NOT NULL,
	category_name varchar(50) NULL
)
;

CREATE TABLE "M2M_Product_Size_Color"
(
	"M2M_PSC_id" bigint NOT NULL   DEFAULT NEXTVAL(('"m2m_product_size_color_m2m_psc_id_seq"'::text)::regclass),
	"M2M_PSC_product_id" bigint NOT NULL,
	"M2M_PSC_size_id" integer NOT NULL,
	"M2M_PSC_color_id" smallint NOT NULL,
	"M2M_PSC_quantity" integer NULL
)
;

CREATE TABLE "Product"
(
	product_id bigint NOT NULL   DEFAULT NEXTVAL(('"product_product_id_seq"'::text)::regclass),
	product_name varchar(50) NULL,
	product_brand_id bigint NOT NULL,
	product_category_id bigint NOT NULL,
	product_price money NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Cart" ADD CONSTRAINT "PK_Cart_User_Product"
	PRIMARY KEY (cart_user_id,cart_product_id)
;

CREATE INDEX "IXFK_Cart_M2M_Product_Size_Color" ON "Cart" (cart_product_id ASC)
;

CREATE INDEX "IXFK_Cart_User" ON "Cart" (cart_user_id ASC)
;

ALTER TABLE "Category" ADD CONSTRAINT "PK_Category"
	PRIMARY KEY (category_id)
;

CREATE INDEX "IXFK_Category_Category" ON "Category" (category_subcategory_id ASC)
;

ALTER TABLE "M2M_Product_Size_Color" ADD CONSTRAINT "PK_M2M_Product_Size_Color"
	PRIMARY KEY ("M2M_PSC_id")
;

CREATE INDEX "IXFK_M2M_Product_Size_Color_Color" ON "M2M_Product_Size_Color" ("M2M_PSC_color_id" ASC)
;

CREATE INDEX "IXFK_M2M_Product_Size_Color_Product" ON "M2M_Product_Size_Color" ("M2M_PSC_product_id" ASC)
;

CREATE INDEX "IXFK_M2M_Product_Size_Color_Size" ON "M2M_Product_Size_Color" ("M2M_PSC_size_id" ASC)
;

ALTER TABLE "Product" ADD CONSTRAINT "PK_Product"
	PRIMARY KEY (product_id)
;

CREATE INDEX "IXFK_Product_Brand" ON "Product" (product_brand_id ASC)
;

CREATE INDEX "IXFK_Product_Category" ON "Product" (product_category_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Cart" ADD CONSTRAINT "FK_Cart_M2M_Product_Size_Color"
	FOREIGN KEY (cart_product_id) REFERENCES "M2M_Product_Size_Color" ("M2M_PSC_id") ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cart" ADD CONSTRAINT "FK_Cart_User"
	FOREIGN KEY (cart_user_id) REFERENCES "User" (user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Category" ADD CONSTRAINT "FK_Category_Category"
	FOREIGN KEY (category_subcategory_id) REFERENCES "Category" (category_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_Product_Size_Color" ADD CONSTRAINT "FK_M2M_Product_Size_Color_Color"
	FOREIGN KEY ("M2M_PSC_color_id") REFERENCES "Color" (color_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_Product_Size_Color" ADD CONSTRAINT "FK_M2M_Product_Size_Color_Product"
	FOREIGN KEY ("M2M_PSC_product_id") REFERENCES "Product" (product_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_Product_Size_Color" ADD CONSTRAINT "FK_M2M_Product_Size_Color_Size"
	FOREIGN KEY ("M2M_PSC_size_id") REFERENCES "Size" (size_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Brand"
	FOREIGN KEY (product_brand_id) REFERENCES "Brand" (brand_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Category"
	FOREIGN KEY (product_category_id) REFERENCES "Category" (category_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE cart_cart_user_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE category_category_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE m2m_product_size_color_m2m_psc_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE product_product_id_seq INCREMENT 1 START 1
;
