/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 24-окт.-2023 18:26:36 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS adress_address_id_seq
;

DROP SEQUENCE IF EXISTS brand_brand_id_seq
;

DROP SEQUENCE IF EXISTS cart_cart_user_id_seq
;

DROP SEQUENCE IF EXISTS category_category_id_seq
;

DROP SEQUENCE IF EXISTS color_color_id_seq
;

DROP SEQUENCE IF EXISTS order_order_id_seq
;

DROP SEQUENCE IF EXISTS product_product_id_seq
;

DROP SEQUENCE IF EXISTS review_review_id_seq
;

DROP SEQUENCE IF EXISTS section_section_id_seq
;

DROP SEQUENCE IF EXISTS size_size_id_seq
;

DROP SEQUENCE IF EXISTS user_user_id_seq
;

/* Drop Tables */

DROP TABLE IF EXISTS "Adress" CASCADE
;

DROP TABLE IF EXISTS "Brand" CASCADE
;

DROP TABLE IF EXISTS "Cart" CASCADE
;

DROP TABLE IF EXISTS "Category" CASCADE
;

DROP TABLE IF EXISTS "Color" CASCADE
;

DROP TABLE IF EXISTS "M2M_order_product" CASCADE
;

DROP TABLE IF EXISTS "M2M_section_category" CASCADE
;

DROP TABLE IF EXISTS "Order" CASCADE
;

DROP TABLE IF EXISTS "Product" CASCADE
;

DROP TABLE IF EXISTS "Review" CASCADE
;

DROP TABLE IF EXISTS "Section" CASCADE
;

DROP TABLE IF EXISTS "Size" CASCADE
;

DROP TABLE IF EXISTS "User" CASCADE
;

/* Create Tables */

CREATE TABLE "Adress"
(
	address_id bigint NOT NULL   DEFAULT NEXTVAL(('"adress_address_id_seq"'::text)::regclass),
	address_user_id bigint NOT NULL,
	address_address varchar(50) NOT NULL
)
;

CREATE TABLE "Brand"
(
	brand_id bigint NOT NULL   DEFAULT NEXTVAL(('"brand_brand_id_seq"'::text)::regclass),
	brand_name varchar(50) NULL
)
;

CREATE TABLE "Cart"
(
	cart_user_id bigint NOT NULL   DEFAULT NEXTVAL(('"cart_cart_user_id_seq"'::text)::regclass),
	cart_product_id bigint NOT NULL,
	cart_quantity smallint NULL
)
;

CREATE TABLE "Category"
(
	category_id bigint NOT NULL   DEFAULT NEXTVAL(('"category_category_id_seq"'::text)::regclass),
	category_subcategory_id bigint NOT NULL,
	category_name varchar(50) NULL
)
;

CREATE TABLE "Color"
(
	color_id smallint NOT NULL   DEFAULT NEXTVAL(('"color_color_id_seq"'::text)::regclass),
	color_name varchar(50) NULL
)
;

CREATE TABLE "M2M_order_product"
(
	m2m_order_product_order_id bigint NOT NULL,
	m2m_order_product_product_id bigint NOT NULL,
	m2m_order_product_quantity varchar(50) NULL
)
;

CREATE TABLE "M2M_section_category"
(
	m2m_section_category_section_id bigint NOT NULL,
	m2m_section_category_category_id bigint NOT NULL
)
;

CREATE TABLE "Order"
(
	order_id bigint NOT NULL   DEFAULT NEXTVAL(('"order_order_id_seq"'::text)::regclass),
	order_price money NULL,
	order_user_id bigint NOT NULL,
	order_address_id bigint NOT NULL,
	order_status integer NOT NULL,
	order_time_create timestamp(6) without time zone NULL
)
;

CREATE TABLE "Product"
(
	product_id bigint NOT NULL   DEFAULT NEXTVAL(('"product_product_id_seq"'::text)::regclass),
	product_name varchar(50) NULL,
	product_brand_id bigint NOT NULL,
	product_category_id bigint NOT NULL,
	product_price money NOT NULL,
	product_quantity integer NOT NULL,
	product_color_id integer NOT NULL,
	product_size_id integer NOT NULL
)
;

CREATE TABLE "Review"
(
	review_id bigint NOT NULL   DEFAULT NEXTVAL(('"review_review_id_seq"'::text)::regclass),
	review_user_id bigint NOT NULL,
	review_product_id bigint NOT NULL,
	review_rating smallint NOT NULL,
	review_comment varchar(200) NULL
)
;

CREATE TABLE "Section"
(
	section_id bigint NOT NULL   DEFAULT NEXTVAL(('"section_section_id_seq"'::text)::regclass),
	section_name varchar(50) NULL
)
;

CREATE TABLE "Size"
(
	size_id integer NOT NULL   DEFAULT NEXTVAL(('"size_size_id_seq"'::text)::regclass),
	size_name varchar(50) NOT NULL
)
;

CREATE TABLE "User"
(
	user_id bigint NOT NULL   DEFAULT NEXTVAL(('"user_user_id_seq"'::text)::regclass),
	user_type smallint NOT NULL,
	user_email varchar(50) NULL,
	user_password varchar(50) NOT NULL,
	user_firstname varchar(50) NULL,
	user_lastname varchar(50) NULL,
	user_phone_number varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Adress" ADD CONSTRAINT "PK_Adress"
	PRIMARY KEY (address_id)
;

CREATE INDEX "IXFK_Adress_User" ON "Adress" (address_user_id ASC)
;

ALTER TABLE "Brand" ADD CONSTRAINT "PK_Brand"
	PRIMARY KEY (brand_id)
;

ALTER TABLE "Cart" ADD CONSTRAINT "PK_Cart_User_Product"
	PRIMARY KEY (cart_user_id,cart_product_id)
;

CREATE INDEX "IXFK_Cart_Product" ON "Cart" (cart_product_id ASC)
;

CREATE INDEX "IXFK_Cart_User" ON "Cart" (cart_user_id ASC)
;

ALTER TABLE "Category" ADD CONSTRAINT "PK_Category"
	PRIMARY KEY (category_id)
;

CREATE INDEX "IXFK_Category_Category" ON "Category" (category_subcategory_id ASC)
;

ALTER TABLE "Color" ADD CONSTRAINT "PK_Color"
	PRIMARY KEY (color_id)
;

CREATE INDEX "IXFK_M2M_order_product_Order" ON "M2M_order_product" (m2m_order_product_order_id ASC)
;

CREATE INDEX "IXFK_M2M_order_product_Product" ON "M2M_order_product" (m2m_order_product_product_id ASC)
;

CREATE INDEX "IXFK_M2M_section_category_Category" ON "M2M_section_category" (m2m_section_category_category_id ASC)
;

CREATE INDEX "IXFK_M2M_section_category_Section" ON "M2M_section_category" (m2m_section_category_section_id ASC)
;

ALTER TABLE "Order" ADD CONSTRAINT "PK_Order"
	PRIMARY KEY (order_id)
;

CREATE INDEX "IXFK_Order_Adress" ON "Order" (order_address_id ASC)
;

CREATE INDEX "IXFK_Order_User" ON "Order" (order_user_id ASC)
;

ALTER TABLE "Product" ADD CONSTRAINT "PK_Product"
	PRIMARY KEY (product_id)
;

CREATE INDEX "IXFK_Product_Brand" ON "Product" (product_brand_id ASC)
;

CREATE INDEX "IXFK_Product_Category" ON "Product" (product_category_id ASC)
;

CREATE INDEX "IXFK_Product_Color" ON "Product" (product_color_id ASC)
;

CREATE INDEX "IXFK_Product_Size" ON "Product" (product_size_id ASC)
;

ALTER TABLE "Review" ADD CONSTRAINT "PK_Review"
	PRIMARY KEY (review_id)
;

CREATE INDEX "IXFK_Review_Product" ON "Review" (review_product_id ASC)
;

CREATE INDEX "IXFK_Review_User" ON "Review" (review_user_id ASC)
;

ALTER TABLE "Section" ADD CONSTRAINT "PK_Section"
	PRIMARY KEY (section_id)
;

ALTER TABLE "Size" ADD CONSTRAINT "PK_Size"
	PRIMARY KEY (size_id)
;

ALTER TABLE "User" ADD CONSTRAINT "PK_User"
	PRIMARY KEY (user_id)
;

/* Create Foreign Key Constraints */

ALTER TABLE "Adress" ADD CONSTRAINT "FK_Adress_User"
	FOREIGN KEY (address_user_id) REFERENCES "User" (user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cart" ADD CONSTRAINT "FK_Cart_Product"
	FOREIGN KEY (cart_product_id) REFERENCES "Product" (product_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Cart" ADD CONSTRAINT "FK_Cart_User"
	FOREIGN KEY (cart_user_id) REFERENCES "User" (user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Category" ADD CONSTRAINT "FK_Category_Category"
	FOREIGN KEY (category_subcategory_id) REFERENCES "Category" (category_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_order_product" ADD CONSTRAINT "FK_M2M_order_product_Order"
	FOREIGN KEY (m2m_order_product_order_id) REFERENCES "Order" (order_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_order_product" ADD CONSTRAINT "FK_M2M_order_product_Product"
	FOREIGN KEY (m2m_order_product_product_id) REFERENCES "Product" (product_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_section_category" ADD CONSTRAINT "FK_M2M_section_category_Category"
	FOREIGN KEY (m2m_section_category_category_id) REFERENCES "Category" (category_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "M2M_section_category" ADD CONSTRAINT "FK_M2M_section_category_Section"
	FOREIGN KEY (m2m_section_category_section_id) REFERENCES "Section" (section_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Order" ADD CONSTRAINT "FK_Order_Adress"
	FOREIGN KEY (order_address_id) REFERENCES "Adress" (address_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Order" ADD CONSTRAINT "FK_Order_User"
	FOREIGN KEY (order_user_id) REFERENCES "User" (user_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Brand"
	FOREIGN KEY (product_brand_id) REFERENCES "Brand" (brand_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Category"
	FOREIGN KEY (product_category_id) REFERENCES "Category" (category_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Color"
	FOREIGN KEY (product_color_id) REFERENCES "Color" (color_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Product" ADD CONSTRAINT "FK_Product_Size"
	FOREIGN KEY (product_size_id) REFERENCES "Size" (size_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Review" ADD CONSTRAINT "FK_Review_Product"
	FOREIGN KEY (review_product_id) REFERENCES "Product" (product_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE "Review" ADD CONSTRAINT "FK_Review_User"
	FOREIGN KEY (review_user_id) REFERENCES "User" (user_id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE adress_address_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE brand_brand_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE cart_cart_user_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE category_category_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE color_color_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE order_order_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE product_product_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE review_review_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE section_section_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE size_size_id_seq INCREMENT 1 START 1
;

CREATE SEQUENCE user_user_id_seq INCREMENT 1 START 1
;
